### ISSUE TITLE
fuo search 的时候,不显示歌名

### ISSUE THREAD

**Issue by gpncarl** [feeluown/feeluown-netease#23]
<img width="1390" alt="截屏2021-05-05 上午12 11 45" src="https://user-images.githubusercontent.com/38633718/117035273-b3202680-ad36-11eb-8607-9a2a9252f24b.png">

mac上刚用pip安装的应该是最新版本,之前用的老版本还正常,
如果用gui界面搜索是会正常显示网易云的歌名的

**Comment by cosven** [comment]
https://github.com/feeluown/FeelUOwn/commit/2a654fe2d1acf9bc3de7de532584921f1f3de426

在 feeluown 中修复了。
